import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
} from "@react-pdf/renderer";
import type { TripData } from "../../types/itinerary";

type Props = { data: TripData };

export const MyItineraryPDF: React.FC<Props> = ({ data }) => {
  const theme = data.themeColor || "#2563eb";

  const Header = ({ title }: { title: string }) => (
    <View style={[styles.header, { backgroundColor: theme }]}>
      <Text style={styles.headerTitle}>{title}</Text>
      <Text style={styles.brand}>
        VOYAGE<Text style={styles.brandBlue}>OS</Text>
      </Text>
    </View>
  );

  const Footer = ({ right }: { right: string }) => (
    <View style={[styles.footer, { borderTopColor: theme }]}>
      <Text style={styles.footerText}>VOYAGEOS ITINERARY</Text>
      <Text style={styles.footerText}>{right}</Text>
    </View>
  );

  const Card = ({ children }: { children: React.ReactNode }) => (
    <View style={[styles.card, { borderColor: hexToRGBA(theme, 0.22) }]}>
      {children}
    </View>
  );

  return (
    <Document>
      {/* ✅ COVER */}
      <Page size="A4" style={styles.page}>
        <View style={[styles.coverBand, { backgroundColor: theme }]} />
        {data.bgImage ? <Image src={data.bgImage} style={styles.coverImg} /> : null}

        <View style={styles.coverBody}>
          <Text style={styles.coverDuration}>{data.duration}</Text>
          <Text style={[styles.coverTitle, { color: theme }]}>
            {(data.title || "Trip Itinerary").toUpperCase()}
          </Text>
          <View style={[styles.coverLine, { backgroundColor: theme }]} />
          <Text style={styles.coverSub}>Generated by VOYAGEOS</Text>
        </View>

        <Footer right="Cover" />
      </Page>

      {/* ✅ FLIGHTS */}
      {data.flights.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Header title="Flights" />
          <View style={styles.content}>
            {data.flights.map((f) => (
              <Card key={f.id}>
                <Text style={[styles.cardTitle, { color: theme }]}>
                  {f.from} → {f.to}
                </Text>
                <Text style={styles.text}>Date: {f.date}</Text>
                {f.time ? <Text style={styles.text}>Time: {f.time}</Text> : null}
                {f.airline ? <Text style={styles.text}>Airline: {f.airline}</Text> : null}
                {f.flightNo ? <Text style={styles.text}>Flight: {f.flightNo}</Text> : null}
              </Card>
            ))}
          </View>
          <Footer right="Flights" />
        </Page>
      )}

      {/* ✅ HOTELS */}
      {data.hotels.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Header title="Hotels" />
          <View style={styles.content}>
            {data.hotels.map((h) => (
              <Card key={h.id}>
                <Text style={[styles.cardTitle, { color: theme }]}>{h.name}</Text>
                <Text style={styles.text}>City: {h.city}</Text>
                <Text style={styles.text}>Check-in: {h.checkIn}</Text>
                <Text style={styles.text}>Check-out: {h.checkOut}</Text>
                {h.roomType ? <Text style={styles.text}>Room: {h.roomType}</Text> : null}
              </Card>
            ))}
          </View>
          <Footer right="Hotels" />
        </Page>
      )}

      {/* ✅ ACTIVITIES */}
      {data.activities.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Header title="Activities" />
          <View style={styles.content}>
            {data.activities.map((a) => (
              <Card key={a.id}>
                <Text style={[styles.cardTitle, { color: theme }]}>
                  Day {a.day}: {a.title}
                </Text>
                {a.time ? <Text style={styles.text}>Time: {a.time}</Text> : null}
                {a.location ? <Text style={styles.text}>Location: {a.location}</Text> : null}
              </Card>
            ))}
          </View>
          <Footer right="Activities" />
        </Page>
      )}

      {/* ✅ DAY PAGES */}
      {data.days.map((d, idx) => (
        <Page size="A4" style={styles.page} key={d.id}>
          <Header title={`Day ${d.day}`} />
          <View style={styles.content}>
            <Card>
              <Text style={[styles.cardTitle, { color: theme }]}>
                {(d.title || `Day ${d.day}`).toUpperCase()}
              </Text>

              {d.img ? <Image src={d.img} style={styles.dayImg} /> : null}

              <Text style={styles.paragraph}>
                {d.description?.trim()
                  ? d.description
                  : "No description added yet."}
              </Text>
            </Card>
          </View>
          <Footer right={`Day ${idx + 1}`} />
        </Page>
      ))}

      {/* ✅ SUMMARY */}
      <Page size="A4" style={styles.page}>
        <Header title="Summary" />
        <View style={styles.content}>
          <Card>
            <Text style={[styles.cardTitle, { color: theme }]}>Inclusions</Text>
            <Text style={styles.text}>{data.inclusions || "No inclusions added."}</Text>
          </Card>

          <Card>
            <Text style={[styles.cardTitle, { color: theme }]}>Contact</Text>
            <Text style={styles.text}>{data.contactPhone || "No contact added."}</Text>
          </Card>

          <Card>
            <Text style={[styles.cardTitle, { color: theme }]}>Total Days</Text>
            <Text style={styles.text}>{data.days.length}</Text>
          </Card>
        </View>
        <Footer right="End" />
      </Page>
    </Document>
  );
};

/* ✅ helper */
function hexToRGBA(hex: string, alpha: number): string {
  let c = hex.replace("#", "").trim();
  if (c.length === 3) c = c.split("").map((x) => x + x).join("");
  if (c.length !== 6) return `rgba(0,0,0,${alpha})`;

  const r = parseInt(c.slice(0, 2), 16);
  const g = parseInt(c.slice(2, 4), 16);
  const b = parseInt(c.slice(4, 6), 16);

  return `rgba(${r},${g},${b},${alpha})`;
}

const styles = StyleSheet.create({
  page: {
    padding: 0,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
    position: "relative",
  },

  header: {
    paddingHorizontal: 40,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: 900,
    color: "#ffffff",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  brand: {
    fontSize: 14,
    fontWeight: 900,
    color: "#ffffff",
  },
  brandBlue: {
    color: "#60a5fa",
  },

  content: {
    paddingHorizontal: 40,
    paddingVertical: 24,
  },

  footer: {
    position: "absolute",
    bottom: 0,
    left: 40,
    right: 40,
    paddingVertical: 12,
    borderTopWidth: 2,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: 800,
    letterSpacing: 0.5,
  },

  card: {
    borderWidth: 1.4,
    borderRadius: 16,
    padding: 14,
    backgroundColor: "#ffffff",
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 12,
    fontWeight: 900,
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  text: {
    fontSize: 11,
    color: "#334155",
    lineHeight: 1.6,
  },
  paragraph: {
    fontSize: 11,
    color: "#334155",
    lineHeight: 1.8,
    marginTop: 10,
  },

  coverBand: {
    height: 120,
    width: "100%",
  },
  coverImg: {
    position: "absolute",
    top: 80,
    left: 0,
    right: 0,
    height: 520,
    opacity: 0.15,
    objectFit: "cover",
  },
  coverBody: {
    paddingHorizontal: 40,
    paddingTop: 90,
  },
  coverDuration: {
    fontSize: 11,
    fontWeight: 900,
    color: "#64748b",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  coverTitle: {
    fontSize: 40,
    fontWeight: 900,
    textTransform: "uppercase",
    lineHeight: 1.05,
  },
  coverLine: {
    height: 4,
    width: 240,
    borderRadius: 99,
    marginTop: 18,
    marginBottom: 10,
  },
  coverSub: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: 700,
  },

  dayImg: {
    width: "100%",
    height: 250,
    borderRadius: 14,
    objectFit: "cover",
    marginTop: 10,
    marginBottom: 10,
  },
});
